inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-minitest

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Naming/FileName:
  Enabled: false
