inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-minitest

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Naming/FileName:
  Enabled: false
