inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Naming/FileName:
  Enabled: false

# Development dependencies are intentionally declared in the gemspec.
Gemspec/DevelopmentDependencies:
  Enabled: false
